### ISSUE TITLE
pornAddict metric doesn't have a Hebrew wordlist

### ISSUE THREAD

**Issue by gidim** [Nimrod007/GroupWise#10]
We're using the English word list to compute pornAddict which is wrong.
Let's remove this in the meantime.. i'll work on getting a list for that.

**Comment by Nimrod007** [comment]
we can add like 100 Hebrew words for now manually and not remove it (its a funny metric i think)

**Comment by gidim** [comment]
I'm working on a list... should have something soon

**Comment by gidim** [comment]
Generated a new list and added to resources. Also added it to DictionariesActor.scala.
Pushed.
