### ISSUE TITLE
Make repo private

### ISSUE THREAD

**Issue by gidim** [Nimrod007/GroupWise#11]
Can we make this repo private?
I have free private repos but you'll have to move ownership to me

**Comment by Nimrod007** [comment]
only problem is that our app will have problem with the fetch.... do you care that people see this stuff ? if yes we can make it private and use git hook and not regular http to fetch...

**Comment by gidim** [comment]
Ya i prefer it will be private. Maybe i'll just create a new private repo only for issue tracking?

**Comment by Nimrod007** [comment]
clone this 1 and push it to your private repo. ill see how much time will it take me to arrange a git hook in prod (not http)

**Comment by gidim** [comment]
https://github.com/gidim/GroupWize

Let us know when you're done and we'll move there.
