### ISSUE TITLE
WordCloud metric not showing

### ISSUE THREAD

**Issue by Nimrod007** [Nimrod007/GroupWise#3]
the metric is in metadata.json and in the api response
http://api.groupwise.co/api.php?user=chats+56c34b2a&group=84bb49d21e9d06176406f61a0d4ae2a9c367825f

@royherma - please verify its shown in the app

**Comment by royherma** [comment]
As you can see, the data is invalid, I am not getting anything in the `yData` - instead it is all returning under `xData` and thus is not being displayed @Nimrod007  @gidim

**Comment by royherma** [comment]
Found the issue, please pass those `yData` as a `Number` and not a `String` @gidim @Nimrod007

**Comment by Nimrod007** [comment]
np will fix

**Comment by gidim** [comment]
@Nimrod007 - Are you changing this on JavaWordCloudCompute.Java?
If so then you also need to change JavaMostFunnyCalculate.java since I did the same thing there (Actually had to manually convert it to Map<String,String> because that's what calcMetric() returns.)

**Comment by Nimrod007** [comment]
if possible ill convert it after (before DB persist)

**Comment by Nimrod007** [comment]
done

http://api.groupwise.co/api.php?user=chats+56c34b2a&group=f6e6d1aceeb70c79754770168b83e6a27c78544f
