### ISSUE TITLE
add MostFunny to metaData json

### ISSUE THREAD

**Issue by Nimrod007** [Nimrod007/GroupWise#8]
ive pushed it to prod.

nedd to add metaData.json info for this

@gidim - your on it?

**Comment by Nimrod007** [comment]
see:
http://api.groupwise.co/api.php?user=chats+56c34b2a&group=f6e6d1aceeb70c79754770168b83e6a27c78544f

metric id is `MostFunny`

**Comment by gidim** [comment]
Done
